### ISSUE TITLE
dbus interactions

### ISSUE THREAD

**Issue by stevensonmt** [kamek-pf/ntfd#27]
Thanks for this great tool. As an exercise I'm trying to more or less clone it in Elixir/Erlang but don't have access to a fully featured or well documented DBus lib in those languages. I don't really know Haskell so I can't quite figure out how you're setting up the DBus object to have the properties you want. Would you mind pointing me to the code that handles this? Or even better the DBus documentation or tutorial that showed you how to do it in the first place?

**Comment by kamek-pf** [comment]
I did use an existing library, probably not very useful to you since you're not going to write Haskell, but an usage example is here: 
https://github.com/kamek-pf/ntfd/blob/7fb5de92f6930f098800d2f01adf7295d829222b/src/Helpers.hs#L60

I used d-feet to explore DBus methods, you probably want to take a look at this: https://wiki.gnome.org/Apps/DFeet (or the new replacement they mention on that page). You can try querying with `busctl` as well, but I suspect you'll have to write your own DBus integration.
